alpha: 0.5
batch_size: 100
cfg: NO_UKER_regnorm_BraTS_TL2
criterion: jvss
data_dir: C:/Data/BraTS2023Met_RegNorm
dataset: DualData
gpu: '0'
mini_batch_size: 50
name: NO_UKER_regnorm_BraTS_TL2
net: DeepMedic
net_params:
  c: 1
  cout: 2
  m: 150
  n1: 30
  n2: 40
  n3: 50
num_epochs: 300
num_epochs_valid_change: 300
num_patches: 10
opt: Adam
opt_params:
  amsgrad: true
  lr: 0.001
  weight_decay: 0.0001
out: ''
resume: C:/MachineLearning/DeepMedicPytorch/Yixing/NO/NO_UKER_regnorm2/model_last.tar
root: C:/MachineLearning/DeepMedicPytorch/
sample_size: 25
save_freq: 50
schedule:
  150: null
  250: null
seed: 20
start_iter: 0
sub_sample_size: 19
target_size: 9
test_data_dir: C:/Data
test_transforms: TensorType((torch.float32, torch.int64))
train_dir: C:/MachineLearning/DeepMedicPytorch/Yixing/NO
train_list: train.txt
train_transforms: TensorType((torch.float32, torch.float32, torch.int64))
valid_freq: 300
valid_freq_new: 2
valid_list: val.txt
workers: 32
