alpha: null
batch_size: 50
cfg: deepmedic_ce
criterion: cross_entropy
data_dir: C:/Data/MICCAI_BraTS_2018_Data_Training
dataset: DualData
gpu: '1'
mini_batch_size: 50
name: deepmedic_ce
net: DeepMedic
net_params:
  m: 150
  n1: 30
  n2: 40
  n3: 50
num_epochs: 300
num_patches: 20
opt: Adam
opt_params:
  amsgrad: true
  lr: 0.001
  weight_decay: 0.0001
out: ''
root: C:/MachineLearning/DeepMedicPytorch/
sample_size: 25
save_freq: 50
schedule:
  150: null
  250: null
seed: 2001
start_iter: 0
sub_sample_size: 19
target_size: 9
test_data_dir: C:/Data/MICCAI_BraTS_2018_Data_Validation
test_transforms: TensorType((torch.float32, torch.int64))
train_dir: C:/MachineLearning/DeepMedicPytorch/Yixing/train_ckpts
train_list: all.txt
train_transforms: TensorType((torch.float32, torch.float32, torch.int64))
valid_freq: 50
workers: 16
