alpha: 0.5
alpha_kdl: 0.1
batch_size: 100
cfg: GJ_CWT_9_Stanford_LWF
criterion: jvss
data_dir: C:/Data/StanfordMetShare
dataset: DualData
gpu: '0'
mini_batch_size: 50
name: GJ_CWT_9_Stanford_LWF
net: DeepMedic
net_params:
  c: 1
  cout: 2
  m: 150
  n1: 30
  n2: 40
  n3: 50
num_epochs: 20
num_epochs_valid_change: 500
num_patches: 10
opt: Adam
opt_params:
  amsgrad: true
  lr: 0.001
  weight_decay: 0.0001
out: ''
resume: C:/MachineLearning/DeepMedicPytorch/Yixing/GJ_CWT/GJ_CWT_8_UCSF_LWF/model_last.tar
root: C:/MachineLearning/DeepMedicPytorch/
sample_size: 25
save_freq: 50
schedule:
  150: null
  250: null
seed: 10
start_iter: 0
sub_sample_size: 19
target_size: 9
test_data_dir: C:/Data
test_transforms: TensorType((torch.float32, torch.int64))
train_dir: C:/MachineLearning/DeepMedicPytorch/Yixing/GJ_CWT
train_list: train.txt
train_transforms: TensorType((torch.float32, torch.float32, torch.int64))
valid_freq: 500
valid_freq_new: 2
workers: 8
