alpha: 0.5
batch_size: 100
cfg: deepmedic_FT_3_NYU
criterion: jvss
data_dir: C:/Data/NYU_Release2
dataset: DualData
gpu: '0'
mini_batch_size: 50
name: deepmedic_FT_3_NYU
net: DeepMedic
net_params:
  c: 1
  cout: 2
  m: 150
  n1: 30
  n2: 40
  n3: 50
num_epochs: 50
num_patches: 10
opt: Adam
opt_params:
  amsgrad: true
  lr: 0.001
  weight_decay: 0.0001
out: ''
resume: C:/MachineLearning/DeepMedicPytorch/Yixing/CL_FT_UKERlast/deepmedic_FT_2_BraTS/model_best.tar
root: C:/MachineLearning/DeepMedicPytorch/
sample_size: 25
save_freq: 50
schedule:
  150: null
  250: null
seed: 2001
start_iter: 0
sub_sample_size: 19
target_size: 9
test_data_dir: C:/Data/NYU_Release2
test_transforms: TensorType((torch.float32, torch.int64))
train_dir: C:/MachineLearning/DeepMedicPytorch/Yixing/CL_FT_UKERlast
train_list: train.txt
train_transforms: TensorType((torch.float32, torch.float32, torch.int64))
valid_freq: 5
valid_list: val.txt
workers: 32
