alpha: 0.5
batch_size: 100
cfg: deepmedic_vss_UCSF_Parcellation
criterion: jvss
data_dir: C:/Data/UCSF_BrainMetastases_v1.2/train_parcellation
dataset: DualData
gpu: '0'
mini_batch_size: 100
name: deepmedic_vss_UCSF_Parcellation
net: DeepMedic
net_params:
  c: 2
  cout: 2
  m: 150
  n1: 30
  n2: 40
  n3: 50
num_epochs: 300
num_epochs_valid_change: 500
num_patches: 20
opt: Adam
opt_params:
  amsgrad: true
  lr: 0.001
  weight_decay: 0.0001
out: ''
root: C:/MachineLearning/DeepMedicPytorch/
sample_size: 25
save_freq: 50
schedule:
  150: null
  250: null
seed: 2001
start_iter: 0
sub_sample_size: 19
target_size: 9
test_data_dir: C:/Data/UCSF_BrainMetastases_v1.2/test_parcellation
test_transforms: TensorType((torch.float32, torch.int64))
train_dir: C:/MachineLearning/DeepMedicPytorch/Yixing/BrainParcellation
train_list: train.txt
train_transforms: TensorType((torch.float32, torch.float32, torch.int64))
valid_freq: 301
valid_freq_new: 500
valid_list: val.txt
workers: 32
